#!/bin/sh

extra=
if test `erl -version 2>&1 | perl -lane 'print $F[-1]'` = "5.9.3.1" ; then
  echo "r15b"
  extra="-mondemand r15b_workaround 'true'"
fi

deps=
for d in deps/* ; do
  deps="$deps -pa $d/ebin"
done
exec erl \
  -name md_client -setcookie md \
  $deps \
  -pa ebin \
  -config mondemand_dev.config \
  $extra \
  -s reloader \
  -s mondemand_app
